### ISSUE TITLE
OpenRAVE Markers tab loops on error

### ISSUE THREAD

**Issue by stephane-caron** [personalrobotics/or_rviz#20]
Hi there,

Running or_rviz for the first time, my "Global Options -> Fixed Frame" was already set to some value, and it generated the following error: nothing was showing in the vizualization, and in OpenRAVE Markers, the Status kept blinking between OK and an error message (sorry it blinks too fast for me to read it). The OK message is:

```
Initialization: Waiting for first update/keep-alive message.
```

Changing Fixed Frame to a random value clears the issue and the model shows up.

After I removed my ~/.rviz folder, the problem stopped showing.

By the way, what value should be set in "Global Options -> Fixed Frame" ?

**Comment by mkoval** [comment]
You should set `Global Options > Fixed Frame` however you normally do in RViz. This is typically the `/map` frame or another frame that is fixed w.r.t. the world. The [RViz documentation](http://wiki.ros.org/rviz/UserGuide#The_Fixed_Frame) has good documentation on the implications of this.

The `or_rviz` world frame defines which TF frame should be treated as the OpenRAVE world frame. This is typically the same as the fixed frame, so it defaults to the current value of `Global Options > Fixed Frame` (this is what the `<Fixed Frame>` option does). 

Clearing your RViz configuration resets both of these values. If the `OpenRAVE Markers` status keeps blinking, then you most likely have a TF problem. Are you sure that your fixed frame and world frame are both valid?

**Comment by mkoval** [comment]
@Tastalian Did you figure out what the cause of this problem was?

**Comment by stephane-caron** [comment]
Thanks for your detailed answer!

Unfortunately I can't tell you more on how this happened, as I haven't been able to reproduce the bug since I deleted my `~/.rviz` folder.

**Comment by mkoval** [comment]
Well, I'm glad it's fixed - even if we don't know why. :smile: 

I'm closing this bug for now. If you see the issue again, please post the offending `.rviz` config file so I can reproduce it.
