### ISSUE TITLE
Move handle with Reset DOF Values

### ISSUE THREAD

**Issue by stephane-caron** [personalrobotics/or_rviz#21]
Hi,

This is more a feature request than a bug: when resetting DOF values, could the handle of the end-effector of the active manipulator move back as well?

In the case I'm working on, the end-effector has a narrow feasible region around its current pose, and finding it back by hand is hard...

**Comment by mkoval** [comment]
This is definitely a bug. The handles are supposed to reset when you `SetDOFValues.` on the ghost manipulation.

It should be a relatively simple fix, so I'll take a look at it this weekend.
