### ISSUE TITLE
Redundant lighting washes out mesh colors.

### ISSUE THREAD

**Issue by psigen** [personalrobotics/or_rviz#28]
When using ROS Indigo `or_rviz` in-process, the default lighting in RViz is not removed before adding the additional lights here:

https://github.com/personalrobotics/or_rviz/blob/732d4c3e40ba0d73f86042835d3a56a6319cc6ed/src/RVizViewer.cpp#L417

This makes the entire scene incredibly washed out.  Most meshes are nearly pure white.

**Comment by mklingen** [comment]
isn't an issue for herb, but I guess other meshes have too much light. I will look into just deleting the existing light.

**Comment by mklingen** [comment]
this commit https://github.com/personalrobotics/or_rviz/commit/0b5244d3f3472f7ac9735205b5502c4189f4d270 added some lighting options in the environment display which should make this more acceptable to your needs. 

![http://i.imgur.com/amtkvot.png](http://i.imgur.com/amtkvot.png)

**Comment by psigen** [comment]
yay! :+1:
