### ISSUE TITLE
Not Able to Build the Plugin 

### ISSUE THREAD

**Issue by jclinton830** [personalrobotics/or_rviz#45]
Hi,

I cloned the or_rviz and openrave_catkin packages into my src folder within my catkin workspace and ran the catkin_make command resulting with the following error. 

.....

[ 41%] Built target industrial_msgs_generate_messages_py
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
or_rviz/CMakeFiles/or_rviz_rviz.dir/build.make:62: recipe for target 'or_rviz/include/or_rviz/rviz/moc_EnvironmentDisplay.cxx' failed
make[2]: *** [or_rviz/include/or_rviz/rviz/moc_EnvironmentDisplay.cxx] Error 1
CMakeFiles/Makefile2:9275: recipe for target 'or_rviz/CMakeFiles/or_rviz_rviz.dir/all' failed
make[1]: *** [or_rviz/CMakeFiles/or_rviz_rviz.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 41%] Built target industrial_msgs_generate_messages
[ 52%] Built target simple_message
[ 65%] Built target simple_message_float64
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

......

I am running ROS Kinetic on Ubuntu 16 in a virtual machine. 

Any help in this matter would be appreciated. Thank you.

**Comment by lakshmip001** [comment]
I face same problem, any leads for these error?

**Comment by chsahit** [comment]
@lakshmip001 @jclinton830 did either of you find a solution to this? Thanks!

**Comment by kvdeepak** [comment]
https://answers.ros.org/question/233786/parse-error-at-boost_join/
https://pastebin.com/5QMFMMs0

This resolves the compilation error but rviz still does not work.
It throws the following error when I run test.py
2019-05-29 12:17:32,104 openrave [WARN] [plugindatabase.h:929 RaveDatabase::_SysLoadLibrary] /home/user/or/devel/share/openrave-0.9/plugins/or_rviz_plugin.so: /home/deepak/or/devel/lib/libor_rviz.so: undefined symbol: _ZThn40_N4rviz18VisualizationFrame15getParentWindowEv
2019-05-29 12:17:32,104 openrave [WARN] [plugindatabase.h:857 RaveDatabase::PluginPtr OpenRAVE::RaveDatabase::_LoadPlugin] failed to load: /home/user/or/devel/share/openrave-0.9/plugins/or_rviz_plugin.so
Segmentation fault (core dumped)

Any help is appreciated.

**Comment by nehagarg** [comment]
> https://answers.ros.org/question/233786/parse-error-at-boost_join/
> https://pastebin.com/5QMFMMs0
> 
> This resolves the compilation error but rviz still does not work.
> It throws the following error when I run test.py
> 2019-05-29 12:17:32,104 openrave [WARN] [plugindatabase.h:929 RaveDatabase::_SysLoadLibrary] /home/user/or/devel/share/openrave-0.9/plugins/or_rviz_plugin.so: /home/deepak/or/devel/lib/libor_rviz.so: undefined symbol: _ZThn40_N4rviz18VisualizationFrame15getParentWindowEv
> 2019-05-29 12:17:32,104 openrave [WARN] [plugindatabase.h:857 RaveDatabase::PluginPtr OpenRAVE::RaveDatabase::_LoadPlugin] failed to load: /home/user/or/devel/share/openrave-0.9/plugins/or_rviz_plugin.so
> Segmentation fault (core dumped)
> 
> Any help is appreciated.

I am also facing the same issue while runnig on ubuntu 18. Please help.
